presentation.pdf: presentation.tex ft.png loom.png monkey.png scummvm_icon_big.png scummvm_logo.pdf
	pdflatex presentation
	pdflatex presentation

scummvm_logo.pdf: ../scummvm_logo.pdf
	cp $< $@

scummvm_icon_big.png: ../scummvm_icon.png
	cp $< $@
